import json
import pathlib
import subprocess
import sys

SUM = "artifacts/releases/integrity_summary.json"


def run(argv):
    return subprocess.run([sys.executable, *argv], check=True, capture_output=True, text=True)


def test_integrity_summary_smoke():
    # ensure perf/e2e exist (generated by your regular gates)
    pathlib.Path("artifacts/perf").mkdir(parents=True, exist_ok=True)
    # produce summary
    run(
        [
            "scripts/inference/integrity_summary.py",
            "--manifest",
            "deploy/models/manifest.json",
            "--out",
            SUM,
        ]
    )
    s = json.load(open(SUM))
    assert "models" in s and s["models"], "no models in summary"
    # known keys (names from your manifest)
    for k in ["perception.depth", "control.policy"]:
        assert k in s["models"], f"missing {k} in summary"
        rec = s["models"][k]
        assert rec.get("sha256_computed"), "no computed sha"
        assert rec.get("inputs") and rec.get("outputs"), "no IO detected"
