repos:
- repo: local
  hooks:
  - id: ruff-format
    name: ruff (format)
    entry: ruff format
    language: system
    types: [python]

  - id: isort
    name: isort
    entry: isort
    language: system
    types: [python]

  - id: black
    name: black
    entry: black
    language: system
    types: [python]

  - id: ruff-lint
    name: ruff (lint + fix)
    entry: ruff check --fix --unsafe-fixes
    language: system
    types: [python]

  # Scope flake8 to perception folder only
  - id: flake8-perception
    name: flake8 (perception-only)
    entry: flake8
    language: system
    files: ^training/scripts/perception/
