repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '^(mlruns/|artifacts/|datasets/|logs/|tmp/)'
      - id: end-of-file-fixer
        exclude: '^(mlruns/|artifacts/|datasets/|logs/|tmp/)'

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length=100"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
