# Northstrike pre-commit (scoped)
repos:
  # --- Hygiene hooks (scoped away from generated content) ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(mlruns/|artifacts/|datasets/|docs/perf/baselines/|artifacts/perf/|artifacts/releases/)
      - id: end-of-file-fixer
        exclude: ^(mlruns/|artifacts/|datasets/|docs/perf/baselines/|artifacts/perf/|artifacts/releases/)

  # --- Black (formatter) — scope to our maintained Python dirs ---
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length", "100"]
        files: ^(scripts/inference/|scripts/datasets/|simulation/domain_randomization/scripts/).+\.py$

  # --- Ruff (linter+fix) — same scope as Black ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: ["--fix"]
        files: ^(scripts/inference/|scripts/datasets/|simulation/domain_randomization/scripts/).+\.py$

  # --- Local project hooks (keep ONNX gates) ---
  - repo: local
    hooks:
      - id: onnx-contracts
        name: onnx-contracts
        language: system
        entry: python scripts/inference/check_onnx_contracts.py --config docs/perf/budgets.yaml --outdir artifacts/perf
        pass_filenames: false
        files: ^(artifacts/onnx/.*\.onnx|docs/perf/budgets\.yaml)$

      - id: onnx-normalize-stable
        name: onnx-normalize-stable
        language: system
        entry: python scripts/inference/normalize_onnx_stable.py
        pass_filenames: true
        files: ^artifacts/onnx/.*\.onnx$
        exclude: _promote_.*\.onnx$

  - repo: local
    hooks:
      - id: repo-doctor
        name: repo-doctor
        entry: python scripts/dev/repo_doctor.py
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
