repos:
  - repo: local
    hooks:
      - id: onnx-contracts
        name: onnx-contracts
        language: system
        entry: python scripts/inference/check_onnx_contracts.py --config docs/perf/budgets.yaml --outdir artifacts/perf
        pass_filenames: false
        files: ^artifacts/onnx/(?!_promote_).+\.onnx$

      - id: onnx-normalize
        name: onnx-normalize
        language: system
        entry: python scripts/inference/normalize_onnx.py
        files: ^artifacts/onnx/(?!_promote_).+\.onnx$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: '^(mlruns/|artifacts/|datasets/|logs/|tmp/)'
      - id: end-of-file-fixer
        exclude: '^(mlruns/|artifacts/|datasets/|logs/|tmp/)'

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length=100"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
