repos:
-   repo: local
    hooks:
    -   id: onnx-contracts
        name: onnx-contracts
        entry: python scripts/inference/check_onnx_contracts.py --config docs/perf/budgets.yaml --outdir artifacts/perf
        language: system
        pass_filenames: false
    -   id: onnx-normalize
        name: onnx-normalize
        entry: python scripts/inference/normalize_onnx.py
        language: system
        pass_filenames: false
    -   id: black
        name: black
        entry: black .
        language: system
        pass_filenames: false
    -   id: isort
        name: isort
        entry: isort .
        language: system
        pass_filenames: false
