repos:
- repo: local
  hooks:
  - id: onnx-contracts
    name: onnx-contracts
    entry: python scripts/inference/check_onnx_contracts.py --config docs/perf/budgets.yaml --outdir artifacts/perf
    language: system
    pass_filenames: false
    stages: [pre-commit]
- repo: local
  hooks:
  - id: onnx-normalize
    name: onnx-normalize
    entry: python scripts/inference/normalize_onnx.py
    language: system
    files: ^artifacts/onnx/.*\.onnx$
    pass_filenames: true
