# Northstrike pre-commit (scoped)
minimum_pre_commit_version: "3.5.0"
repos:
  # --- Hygiene hooks (ignore generated/large artifacts) ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '^(mlruns/|artifacts/|datasets/|docs/perf/baselines/|artifacts/perf/|artifacts/releases/)'
      - id: end-of-file-fixer
        exclude: '^(mlruns/|artifacts/|datasets/|docs/perf/baselines/|artifacts/perf/|artifacts/releases/)'

  # --- Black (formatter) — only maintained Python dirs ---
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length", "100"]
        files: '^(src/|tests/|training/|benchmarks/|scripts/(inference|datasets|estimation|maps)/|simulation/domain_randomization/).+\.py$'

  # --- Ruff (linter/fixes) ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: ["--fix", "--unsafe-fixes"]
        files: '^(src/|tests/|training/|benchmarks/|scripts/(inference|datasets|estimation|maps)/|simulation/domain_randomization/).+\.py$'

  # --- isort (import order, Black profile) ---
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", "--line-length", "100"]
        files: '^(src/|tests/|training/|benchmarks/|scripts/(inference|datasets|estimation|maps)/|simulation/domain_randomization/).+\.py$'

  # --- Local hooks: ONNX gates on pre-push only (keep PR fast) ---
  - repo: local
    hooks:
      - id: onnx-normalize-stable
        name: onnx-normalize-stable
        entry: python scripts/inference/onnx_normalize_stable.py
        language: system
        files: '\.onnx$'
        stages: [pre-push]
      - id: onnx-contracts
        name: onnx-contracts
        entry: python scripts/inference/check_onnx_contracts.py --config docs/perf/budgets.yaml --outdir artifacts/perf
        language: system
        pass_filenames: false
        stages: [pre-push]
