repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        # If you already use a baseline, uncomment the next line:
        # args: ["--baseline", ".secrets.baseline"]

  # Local hook for dataset QA (safe no-op if paths are missing)
  - repo: local
    hooks:
      - id: label-qa
        name: Dataset QA (YOLO)
        entry: bash scripts/labeling/precommit_label_qa.sh
        language: system
        pass_filenames: false
        stages: [pre-commit]

