[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"

[tool.ruff]
target-version = "py310"
line-length = 100
extend-exclude = ["sim/scripts/_archive/**"]
force-exclude = true
fix = true
unsafe-fixes = true

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "I"]
ignore = ["E203"]

[tool.ruff.lint.per-file-ignores]
"training/tests/**" = ["E501", "B904"]
"training/scripts/**" = ["E501"]
"scripts/**" = ["E501"]
"sim/scripts/**" = ["E501", "B904"]
"sim/ns_train_depth_baseline.py" = ["E501"]
"training/src/domain/wind.py" = ["B008"]

[tool.pytest.ini_options]
testpaths = ["training/tests"]
pythonpath = ["training", "sim"]
