[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
target-version = "py310"
fix = true
unsafe-fixes = false

[tool.ruff.lint]
select = ["E", "F", "B", "UP", "I"]
ignore = ["E203"]  # Black compat

[tool.ruff.lint.per-file-ignores]
"training/tests/**" = ["E501"]      # long lines okay in tests
"scripts/**"        = ["E501"]      # long CLI strings okay in scripts
"sim/scripts/**"    = ["E501"]
