[tool.black]
line-length = 100
target-version = ["py310"]

[tool.pytest.ini_options]
testpaths = ["training/tests"]
pythonpath = ["training", "sim"]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
ignore = ["E203"]

[tool.ruff.lint.per-file-ignores]
"scripts/inference/*.py" = ["E501"]  # allow long prints in CLI scripts
