[tool.black]
line-length = 100
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 100

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "UP", "B"]
ignore = ["E203"]
# Exclude heavy directories from linting (optional)
exclude = ["sim", "training", ".venv", "datasets"]
