name: ci-gate
on:
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: {}
jobs:
  gate:
  gate:  if: ${{ github.event_name != "pull_request" }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      with:
        lfs: true
        fetch-depth: 0
        with: { lfs: true }
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - run: .github/scripts/ci_gate.sh
