name: ci-gate
true:
  pull_request:
    branches:
    - '**'
  workflow_dispatch: {}
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: .github/scripts/ci_gate.sh
