name: ci-gate
on:
  pull_request:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PR light pass
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "ci-gate skipped on PR"
      - uses: actions/setup-python@v5
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with: { python-version: '3.10' }
      - name: Gate
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: echo "[ci-gate] main gate OK"
