name: ci-smoke
on:
  pull_request:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { lfs: true, fetch-depth: 0 }
      - name: PR light pass
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "smoke skipped on PR"
      - uses: actions/setup-python@v5
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with: { python-version: '3.10', cache: 'pip' }
      - name: Install + hydrate + smoke
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          python -m pip install -U pip
          pip install pytest onnx onnxruntime numpy pyyaml
          git lfs fetch --all || true
          git lfs checkout || true
          pytest -q || true
