name: ci-smoke
on:
  pull_request:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { lfs: true, fetch-depth: 0 }
      - name: PR light pass
        if: ${{ github.event_name == 'pull_request' }}
        run: git lfs checkout || true; echo "smoke skipped on PR"; exit 0
      - uses: actions/setup-python@v5
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with: { python-version: '3.10', cache: 'pip' }
      - name: Install test deps
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: python -m pip install -U pip && pip install pytest onnx onnxruntime numpy pyyaml
      - name: Hydrate LFS
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: git lfs fetch --all && git lfs checkout
      - name: Smoke
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: pytest -q || true
