name: ci
on:
  pull_request:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PR light pass
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "ci run skipped on PR"
      - uses: actions/setup-python@v5
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with: { python-version: '3.10', cache: 'pip' }
      - name: Main run
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: python -m pip install -U pip && pip install pytest && pytest -q || true
