name: CI

on:
  push:
  pull_request:

jobs:
  python:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          # optional: install your package if/when you make it one
          # pip install -e .

      - name: Lint (black/isort/flake8)
        run: |
          black --check .
          isort --check-only .
          flake8

      - name: Unit tests (pytest)
        run: |
          pytest -q
