name: datasets-verify
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      force:
        description: 'Force run even if datasets/public/** is absent'
        type: boolean
        default: false

jobs:
  verify:
    # On PRs: always run (step non-blocking).
    # On push→main: run only if datasets exist.
    # On manual dispatch: run if inputs.force==true.
    if: ${{ github.event_name != 'push'
           || hashFiles('datasets/public/**') != ''
           || (github.event_name == 'workflow_dispatch' && inputs.force) }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with: { lfs: true, fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python deps (light)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          pip install pyyaml jsonschema numpy pandas tqdm

      - name: Verify (non-blocking on PR)
        if: github.event_name == 'pull_request'
        run: mkdir -p artifacts/perf && python scripts/data/verify_public.py --json-out artifacts/perf/datasets_verify_ci.json
        continue-on-error: true

      - name: Verify (blocking on push/dispatch)
        if: github.event_name != 'pull_request'
        run: mkdir -p artifacts/perf && python scripts/data/verify_public.py --json-out artifacts/perf/datasets_verify_ci.json

      - name: Upload verify report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: datasets-verify-${{ github.run_id }}
          path: artifacts/perf/datasets_verify_ci.json
          if-no-files-found: ignore
