name: datasets-verify
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with: { lfs: true, fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python deps (light)
        run: |
          python -m pip install -U pip
          # Try project requirements if present, but don't fail the job if missing
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          # Minimal libs commonly needed by verify scripts
          pip install pyyaml jsonschema numpy pandas tqdm
      - name: Verify (non-blocking on PR)
        if: github.event_name == 'pull_request'
        run: mkdir -p artifacts/perf && python scripts/data/verify_public.py --json-out artifacts/perf/datasets_verify_ci.json
        continue-on-error: true
      - name: Verify (blocking on push)
        if: github.event_name != 'pull_request'
        run: mkdir -p artifacts/perf && python scripts/data/verify_public.py --json-out artifacts/perf/datasets_verify_ci.json
