name: datasets-verify
on:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "datasets verify runs on push→main only"
