name: datasets-verify
on:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { lfs: true, fetch-depth: 0 }
      - run: git lfs fetch --all && git lfs checkout
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Verify public datasets scaffold
        run: python scripts/data/verify_public.py --json-out artifacts/perf/datasets_verify_ci.json
