name: maps-smoke
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  smoke:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with: { lfs: true, fetch-depth: 0 }
      - name: Install GDAL
        run: sudo apt-get update && sudo apt-get install -y gdal-bin python3-gdal
      - name: Maps smoke (toronto_downtown)
        run: bash scripts/maps/smoke_prep_and_make.sh toronto_downtown
