name: maps-smoke
on:
  pull_request:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  smoke:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with: { lfs: true, fetch-depth: 0 }
      - name: PR light pass
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "maps-smoke skipped on PR"; exit 0
      - run: git lfs fetch --all && git lfs checkout
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      - name: Install GDAL
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin
      - name: Maps smoke (toronto_downtown)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: make maps-smoke AREA=toronto_downtown N=20
      - name: Publish bundle (no upload)
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          make maps-publish AREA=toronto_downtown
          ls -lh artifacts/maps || true
      - name: Show readback/parity summaries
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |
          ls -1 maps/reports || true
          find artifacts/maps -maxdepth 1 -type f -name '*.zip*' -ls || true
