name: maps-smoke
on:
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true  # fetch LFS pointers if present
      - name: Install GDAL
        run: sudo apt-get update && sudo apt-get install -y gdal-bin python3-gdal
      - name: Maps smoke (toronto_downtown)
        run: bash scripts/maps/smoke_prep_and_make.sh toronto_downtown
