name: maps-smoke
on:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "maps smoke runs on push→main only"
