name: maps-smoke
on:
  push:
  pull_request:

jobs:
  smoke:
    # Skip heavy maps smoke on PRs; still runs on push/nightly
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Install GDAL
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin

      # Ensure Python is available in case make targets import Python libs
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python deps (best effort)
        run: |
          python -m pip install -U pip wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Maps smoke (toronto_downtown)
        run: |
          make maps-smoke AREA=toronto_downtown N=20

      - name: Publish bundle (no upload, just build + sha)
        run: |
          make maps-publish AREA=toronto_downtown
          ls -lh artifacts/maps || true

      - name: Show readback/parity summaries
        run: |
          ls -1 maps/reports || true
          find artifacts/maps -maxdepth 1 -type f -name '*.zip*' -ls || true
