name: nightly-eval
on: { schedule: [{ cron: "0 3 * * *" }], workflow_dispatch: {} }
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { lfs: true }
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - run: pip install -U pip && pip install onnx onnxruntime pyyaml numpy
      - run: .github/scripts/nightly.sh
