name: ONNX Gates
on:
  push:
  pull_request:

jobs:
  onnx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-perf.txt
      - name: Contracts
        run: |
          python scripts/inference/check_onnx_contracts.py \
            --config docs/perf/budgets.yaml --outdir artifacts/perf
      - name: Perf
        run: |
          python scripts/inference/profile_onnx.py \
            --config docs/perf/budgets.yaml --outdir artifacts/perf --check
      - name: Tests (offline, e2e, promote)
        run: |
          python -m pip install -U pip && pip install pytest && pytest -q \
            training/tests/inference/test_depth_offline_smoke.py \
            training/tests/inference/test_policy_offline_smoke.py \
            training/tests/inference/test_e2e_tick_smoke.py \
            training/tests/inference/test_promote_model_smoke.py
      - name: Upload perf artifacts
        uses: actions/upload-artifact@v4
        with:
          name: perf-json
          path: artifacts/perf/
