name: onnx-gates
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  onnx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Prepare env & dummy policy
        run: bash scripts/ci/prepare_pr_env.sh
      - name: ONNX verify
        run: make onnx-verify
      - name: ONNX regress
        run: make onnx-regress
