name: ONNX Gates
true:
  push: null
  pull_request: null
jobs:
  onnx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install deps
      run: 'python -m pip install --upgrade pip

        pip install -r requirements-perf.txt

        '
    - name: Contracts
      run: "python scripts/inference/check_onnx_contracts.py \\\n  --config docs/perf/budgets.yaml\
        \ --outdir artifacts/perf\n"
    - name: Perf
      run: "python scripts/inference/profile_onnx.py \\\n  --config docs/perf/budgets.yaml\
        \ --outdir artifacts/perf --check\n"
    - name: Tests (offline, e2e, promote)
      run: "pytest -q \\\n  training/tests/inference/test_depth_offline_smoke.py \\\
        \n  training/tests/inference/test_policy_offline_smoke.py \\\n  training/tests/inference/test_e2e_tick_smoke.py\
        \ \\\n  training/tests/inference/test_promote_model_smoke.py\n"
    - name: Upload perf artifacts
      uses: actions/upload-artifact@v4
      with:
        name: perf-json
        path: artifacts/perf/
