name: onnx-gates

on:
  pull_request:
    paths:
      - "scripts/inference/**"
      - "training/tests/inference/**"
      - "deploy/models/**"
      - ".github/workflows/onnx-gates.yml"
      - "requirements.txt"
  workflow_dispatch:

jobs:
  onnx:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10 (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt

      - name: Build dummy policy ONNX (IR=10, opset=13)
        run: |
          mkdir -p artifacts/onnx
          python scripts/inference/make_dummy_policy_onnx.py \
            --in-dim 64 --out-dim 4 \
            --out artifacts/onnx/policy_dummy.onnx
          python - <<'PY'
          import onnx, pathlib
          p = pathlib.Path("artifacts/onnx/policy_dummy.onnx")
          m = onnx.load(str(p))
          assert p.is_file(), "policy file missing"
          assert m.ir_version == 10, f"IR version mismatch: {m.ir_version}"
          assert any((i.domain in ("", "ai.onnx")) and i.version == 13 for i in m.opset_import), f"bad opsets: {m.opset_import}"
          print("OK: dummy policy exists; IR=10; opset=13")
          PY

      - name: Verify manifest hashes
        run: |
          python scripts/inference/verify_manifest_hashes.py \
            --manifest deploy/models/manifest.json --check

      - name: Inference smoke tests
        run: |
          pytest -q training/tests/inference
