name: onnx-gates

on:
  pull_request:

jobs:
  onnx:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"  # built-in pip cache

      - name: Install minimal deps for ONNX gates
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade onnx onnxruntime pytest

      - name: Build deterministic dummy policy (IR=10, opset=13)
        run: |
          mkdir -p artifacts/onnx
          # guard against dead symlink or stale file
          [ -L artifacts/onnx/policy_dummy.onnx ] || [ -e artifacts/onnx/policy_dummy.onnx ] && rm -f artifacts/onnx/policy_dummy.onnx
          python scripts/inference/make_dummy_policy_onnx.py \
            --in-dim 64 --out-dim 4 \
            --out artifacts/onnx/policy_dummy.onnx

      - name: Sanity: print IR/opset
        run: |
          python - <<'PY'
          import onnx, pathlib
          p = pathlib.Path("artifacts/onnx/policy_dummy.onnx")
          m = onnx.load(str(p))
          print("EXISTS:", p.is_file(), "IR:", m.ir_version, "opsets:", [(i.domain, i.version) for i in m.opset_import])
          PY

      - name: Verify manifest hashes (must be OK)
        run: python scripts/inference/verify_manifest_hashes.py --manifest deploy/models/manifest.json --check

      - name: Inference smoke tests
        run: |
          pytest -q training/tests/inference/test_policy_offline_smoke.py
          pytest -q training/tests/inference/test_e2e_tick_smoke.py
          pytest -q training/tests/inference/test_verify_manifest_hashes.py
