name: repo-doctor
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install git-lfs
        run: |
          sudo apt-get update && sudo apt-get install -y git-lfs
          git lfs install
      - name: Repo Doctor
        run: python scripts/dev/repo_doctor.py
