name: Simulation Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  sim:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install -e .
      - name: Run simulation smoke tests
        run: pytest -q tests/simulation --maxfail=1 --disable-warnings
