name: stack-smoke
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      with:
        lfs: true
        fetch-depth: 0
        with: { lfs: true }
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - run: pip install -U pip && pip install onnx onnxruntime pyyaml numpy
      - run: python scripts/inference/check_onnx_contracts.py --config docs/perf/budgets.yaml --outdir artifacts/perf
      - run: python scripts/inference/profile_onnx.py --config docs/perf/budgets.yaml --outdir artifacts/perf --check
      - run: python scripts/inference/stack_demo.py
